name: CICD Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI/CD is done"
    steps:
      - run: mkdir pipeline

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI/CD is done"
